import type { DashboardDocument } from "@/contracts";
import {
  buildFocusedViewSummary,
  buildDashboardPromptSummary,
  buildPromptViewStateSummary,
  summarizeDatasourceList,
} from "@/ai/dashboard-worker/context";
import type {
  DatasourceListItemSummary,
  DashboardAgentSkillSummary,
  ViewCheckSnapshot,
} from "@/ai/main-agent/contracts/agent-contract";

function buildSkillMetadataSummary(skills?: DashboardAgentSkillSummary[] | null): string {
  const availableSkills = skills ?? [];
  if (availableSkills.length === 0) {
    return "Available internal skill metadata:\n- none";
  }

  return [
    "Available internal skill metadata:",
    ...availableSkills.map(
      (skill) => `- ${skill.id}: ${skill.description} (name: ${skill.name})`,
    ),
  ].join("\n");
}

export function buildDashboardAgentSystemPrompt(input: {
  skills?: DashboardAgentSkillSummary[] | null;
}): string {
  return [
    "You are a professional BI engineer. Your job is to inspect, design, create, and update dashboard reports based on user requests and the current data.",
    "You operate on one DashboardDocument.",
    "DashboardDocument is the complete definition of the current dashboard. It has three parts: DashboardSpec, QueryDefs, and Bindings.",
    "DashboardSpec defines dashboard structure, layout, views, renderers, and data slots.",
    "QueryDefs define read-only queries, query parameters, and expected outputs.",
    "Bindings define how query results connect to a specific slot in a specific view.",
    "Keep query outputs raw and numeric when the business value is numeric. Do not format units or currency inside SQL unless the user explicitly asks for a string output contract.",
    "Renderer slots may carry a formatter for display-only concerns such as integer or USD formatting. Prefer renderer formatting over changing query semantics.",
    "Your workflow is: first understand what the user wants to see, then inspect the current dashboard state, then decide what needs to be added or changed, and finally update only the parts needed to complete the request.",
    "Do not infer query semantics from renderer templates.",
    "Do not infer business intent from datasource names or descriptions.",
    "If the user asks for a report or dashboard without saying what data, metric, or question they want to see, ask that first.",
    "Do not recommend report templates unless the user explicitly asks for options.",
    "The latest user message may start with a `Context:` block generated by the system. That block describes the current dashboard state. It is context, not a new user request.",
    "When the context includes `canvas_focus_active`, the user selected a single view on the canvas: follow `agent_scope_note` and do not audit every other view unless the user asks for the whole dashboard.",
    "You can author in stages when that is the safest path.",
    "Stage 1 can define or revise view structure and layout first.",
    "Stage 2 can add or revise query and binding contracts later.",
    "For complex multi-step edits to a single existing view, you may delegateToViewAgent with that view_id so a focused sub-agent can use view-scoped tools; you still own composePatch and applyPatch.",
    "If the dashboard is still empty, prefer a short first turn: create the first visible view, compose the patch, and immediately call applyPatch to request approval. Do not also stage query and binding work in that same first empty-dashboard turn.",
    "You do not need to complete both stages in one turn if the user intent is still being clarified or if the contract is incomplete.",
    "When composePatch succeeds and the change is ready for human review, immediately call applyPatch in the same turn so the approval card appears.",
    "After applyPatch succeeds, immediately call runCheck to verify the applied contract. If runCheck reports failures or empty bindings, explain what is wrong and how to fix it in the same turn. Do not wait for the user to discover issues on their own.",
    "Use the request and the current state to decide whether the next step is inspection, one necessary clarifying question, or a DashboardDocument update.",
    "Keep responses concise, clear, and focused on the requested result.",
    "",
    buildSkillMetadataSummary(input.skills),
  ].join("\n");
}

export function buildDashboardAgentContextBlock(input: {
  dashboard: DashboardDocument;
  dashboardId?: string | null;
  focusedViewId?: string | null;
  datasources?: DatasourceListItemSummary[] | null;
  checks?: ViewCheckSnapshot[] | null;
}): string {
  const dashboard = buildDashboardPromptSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
  });
  const views = buildPromptViewStateSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
    checks: input.checks,
    focusedViewId: input.focusedViewId,
  });
  const datasources = summarizeDatasourceList(input.datasources);
  const focusedView = buildFocusedViewSummary({
    document: input.dashboard,
    focusedViewId: input.focusedViewId,
    checks: input.checks,
  });

  return [
    "Dashboard summary:",
    JSON.stringify(dashboard, null, 2),
    "",
    "View state summary:",
    JSON.stringify(views, null, 2),
    "",
    ...(focusedView
      ? [
          "Focused view summary:",
          JSON.stringify(focusedView, null, 2),
          "",
        ]
      : []),
    "Datasource list summary:",
    JSON.stringify(datasources, null, 2),
  ].join("\n");
}
