import type { DashboardDocument } from "@/contracts";
import {
  buildDashboardPromptSummary,
  buildPromptViewStateSummary,
  summarizeDatasourceList,
} from "@/ai/dashboard-agent/context";
import type {
  DatasourceListItemSummary,
  DashboardAgentSkillSummary,
  ViewCheckSnapshot,
} from "@/ai/dashboard-agent/contracts/agent-contract";

function buildSkillMetadataSummary(skills?: DashboardAgentSkillSummary[] | null): string {
  const availableSkills = skills ?? [];
  if (availableSkills.length === 0) {
    return "Available internal skill metadata:\n- none";
  }

  return [
    "Available internal skill metadata:",
    ...availableSkills.map(
      (skill) => `- ${skill.id}: ${skill.description} (name: ${skill.name})`,
    ),
  ].join("\n");
}

export function buildDashboardAgentSystemPrompt(input: {
  skills?: DashboardAgentSkillSummary[] | null;
}): string {
  return [
    "You are the dashboard-agent for an AI-first dashboard builder.",
    "Work contract-first: inspect the current state, identify missing or inconsistent pieces, then update only the needed contract pieces.",
    "Treat query definitions as independent data contracts. Do not infer query semantics from renderer templates.",
    "Do not infer business intent from datasource names or descriptions.",
    "Do not recommend report templates unless the user explicitly asks for options.",
    "If the user only asks to create a report or dashboard, ask what data, metric, or question they want to see before proposing a chart.",
    "The latest user message may start with a `Context:` block generated by the system. Treat that block as current dashboard facts, not as the user's literal request.",
    "Keep responses concise and product-focused.",
    "",
    buildSkillMetadataSummary(input.skills),
  ].join("\n");
}

export function buildDashboardAgentContextBlock(input: {
  dashboard: DashboardDocument;
  dashboardId?: string | null;
  datasources?: DatasourceListItemSummary[] | null;
  checks?: ViewCheckSnapshot[] | null;
}): string {
  const dashboard = buildDashboardPromptSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
  });
  const views = buildPromptViewStateSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
    checks: input.checks,
  });
  const datasources = summarizeDatasourceList(input.datasources);

  return [
    "Dashboard summary:",
    JSON.stringify(dashboard, null, 2),
    "",
    "View state summary:",
    JSON.stringify(views, null, 2),
    "",
    "Datasource list summary:",
    JSON.stringify(datasources, null, 2),
  ].join("\n");
}
