import type { DashboardDocument } from "@/contracts";
import {
  buildDashboardPromptSummary,
  buildPromptViewStateSummary,
  summarizeDatasourceList,
} from "@/ai/dashboard-agent/context";
import type {
  DatasourceListItemSummary,
  DashboardAgentSkillSummary,
  ViewCheckSnapshot,
} from "@/ai/dashboard-agent/contracts/agent-contract";

function buildSkillMetadataSummary(skills?: DashboardAgentSkillSummary[] | null): string {
  const availableSkills = skills ?? [];
  if (availableSkills.length === 0) {
    return "Available internal skill metadata:\n- none";
  }

  return [
    "Available internal skill metadata:",
    ...availableSkills.map(
      (skill) => `- ${skill.id}: ${skill.description} (name: ${skill.name})`,
    ),
  ].join("\n");
}

export function buildDashboardAgentSystemPrompt(input: {
  skills?: DashboardAgentSkillSummary[] | null;
}): string {
  return [
    "You are a professional BI engineer. Your job is to inspect, design, create, and update dashboard reports based on user requests and the current data.",
    "You operate on one DashboardDocument.",
    "DashboardDocument is the complete definition of the current dashboard. It has three parts: DashboardSpec, QueryDefs, and Bindings.",
    "DashboardSpec defines dashboard structure, layout, views, renderers, and data slots.",
    "QueryDefs define read-only queries, query parameters, and expected outputs.",
    "Bindings define how query results connect to a specific slot in a specific view.",
    "Your workflow is: first understand what the user wants to see, then inspect the current dashboard state, then decide what needs to be added or changed, and finally update only the parts needed to complete the request.",
    "Do not infer query semantics from renderer templates.",
    "Do not infer business intent from datasource names or descriptions.",
    "If the user asks for a report or dashboard without saying what data, metric, or question they want to see, ask that first.",
    "Do not recommend report templates unless the user explicitly asks for options.",
    "The latest user message may start with a `Context:` block generated by the system. That block describes the current dashboard state. It is context, not a new user request.",
    "Use the request and the current state to decide whether the next step is inspection, one necessary clarifying question, or a DashboardDocument update.",
    "Keep responses concise, clear, and focused on the requested result.",
    "",
    buildSkillMetadataSummary(input.skills),
  ].join("\n");
}

export function buildDashboardAgentContextBlock(input: {
  dashboard: DashboardDocument;
  dashboardId?: string | null;
  datasources?: DatasourceListItemSummary[] | null;
  checks?: ViewCheckSnapshot[] | null;
}): string {
  const dashboard = buildDashboardPromptSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
  });
  const views = buildPromptViewStateSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
    checks: input.checks,
  });
  const datasources = summarizeDatasourceList(input.datasources);

  return [
    "Dashboard summary:",
    JSON.stringify(dashboard, null, 2),
    "",
    "View state summary:",
    JSON.stringify(views, null, 2),
    "",
    "Datasource list summary:",
    JSON.stringify(datasources, null, 2),
  ].join("\n");
}
