export {
  DASHBOARD_COLOR_THEME_ID_PURPLE,
  DASHBOARD_COLOR_THEME_ID_TEAL,
  DASHBOARD_COLOR_THEME_IDS,
  DASHBOARD_DESIGN_KIT_IDS,
  DASHBOARD_VIEW_STYLE_ID_CLEAN,
  DASHBOARD_VIEW_STYLE_ID_EMPHASIS,
  DASHBOARD_VIEW_STYLE_ID_GRADIENT,
  DASHBOARD_VIEW_STYLE_IDS,
  CANONICAL_RUNTIME_DESIGN_KIT_ID,
  EXECUTIVE_REPORT_DESIGN_KIT_ID,
  OPERATIONAL_REPORT_DESIGN_KIT_ID,
} from "./dashboard-presentation-ids";
import {
  DASHBOARD_COLOR_THEME_IDS,
  DASHBOARD_DESIGN_KIT_IDS,
  DASHBOARD_VIEW_STYLE_ID_CLEAN,
  DASHBOARD_VIEW_STYLE_ID_EMPHASIS,
  DASHBOARD_VIEW_STYLE_ID_GRADIENT,
  DASHBOARD_VIEW_STYLE_IDS,
  CANONICAL_RUNTIME_DESIGN_KIT_ID,
  EXECUTIVE_REPORT_DESIGN_KIT_ID,
  OPERATIONAL_REPORT_DESIGN_KIT_ID,
} from "./dashboard-presentation-ids";

export type DashboardDesignKitId = (typeof DASHBOARD_DESIGN_KIT_IDS)[number];
export type DashboardColorThemeId = (typeof DASHBOARD_COLOR_THEME_IDS)[number];
export type DashboardViewStyleId = (typeof DASHBOARD_VIEW_STYLE_IDS)[number];

export function normalizeDashboardDesignKitId(designKitId: string): string {
  const normalized = designKitId.trim();
  if (
    normalized === OPERATIONAL_REPORT_DESIGN_KIT_ID ||
    normalized === EXECUTIVE_REPORT_DESIGN_KIT_ID
  ) {
    return CANONICAL_RUNTIME_DESIGN_KIT_ID;
  }
  return normalized;
}
