import type { DashboardDocument } from "@/contracts";
import {
  buildFocusedViewSummary,
  buildWorkerPromptSummary,
  buildPromptViewStateSummary,
  summarizeDatasourceList,
} from "@/ai/view-worker/context";
import type {
  DatasourceListItemSummary,
  MainAgentSkillSummary,
  ViewCheckSnapshot,
} from "@/ai/main-agent/contracts/agent-contract";

function buildSkillMetadataSummary(skills?: MainAgentSkillSummary[] | null): string {
  const availableSkills = skills ?? [];
  if (availableSkills.length === 0) {
    return "Available internal skill metadata:\n- none";
  }

  return [
    "Available internal skill metadata:",
    ...availableSkills.map(
      (skill) => `- ${skill.id}: ${skill.description} (name: ${skill.name})`,
    ),
  ].join("\n");
}

export function buildWorkerSystemPrompt(input: {
  skills?: MainAgentSkillSummary[] | null;
}): string {
  return [
    "You are a focused BI engineer for exactly one dashboard view.",
    "You operate on one DashboardDocument, but your task scope is limited to the focused view and its related query/binding contracts.",
    "Keep query outputs raw and numeric when the business value is numeric. Do not format units or currency inside SQL unless the user explicitly asks for a string output contract.",
    "Renderer slots may carry a formatter for display-only concerns such as integer or USD formatting. Prefer renderer formatting over changing query semantics.",
    "Never inspect or analyze unrelated views.",
    "Never modify dashboard layout, add/remove views, or make dashboard-wide decisions.",
    "Your workflow is: understand the focused view request, inspect the focused view state, then update only that view and its directly-related query/binding contract.",
    "Do not infer query semantics from renderer templates.",
    "Do not infer business intent from datasource names or descriptions.",
    "The latest user message may start with a `Context:` block generated by the system. That block describes the current dashboard state. It is context, not a new user request.",
    "The context includes a focused view summary. Stay inside that scope.",
    "You can author in stages when that is the safest path.",
    "After applyPatch succeeds, immediately call runCheck to verify the applied contract. If runCheck reports failures or empty bindings, explain what is wrong and how to fix it in the same turn. Do not wait for the user to discover issues on their own.",
    "Use the request and the current state to decide whether the next step is inspection, one necessary clarifying question, or a DashboardDocument update.",
    "Keep responses concise, clear, and focused on the requested result.",
    "",
    buildSkillMetadataSummary(input.skills),
  ].join("\n");
}

export function buildWorkerContextBlock(input: {
  dashboard: DashboardDocument;
  dashboardId?: string | null;
  focusedViewId?: string | null;
  datasources?: DatasourceListItemSummary[] | null;
  checks?: ViewCheckSnapshot[] | null;
}): string {
  const dashboard = buildWorkerPromptSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
  });
  const views = buildPromptViewStateSummary({
    document: input.dashboard,
    dashboardId: input.dashboardId,
    checks: input.checks,
    focusedViewId: input.focusedViewId,
  });
  const datasources = summarizeDatasourceList(input.datasources);
  const focusedView = buildFocusedViewSummary({
    document: input.dashboard,
    focusedViewId: input.focusedViewId,
    checks: input.checks,
  });

  return [
    "Dashboard summary:",
    JSON.stringify(dashboard, null, 2),
    "",
    "View state summary:",
    JSON.stringify(views, null, 2),
    "",
    ...(focusedView
      ? [
          "Focused view summary:",
          JSON.stringify(focusedView, null, 2),
          "",
        ]
      : []),
    "Datasource list summary:",
    JSON.stringify(datasources, null, 2),
  ].join("\n");
}
